#pragma once

#include "Idle.h"
#include "MoveForward.h"
#include "MoveBackward.h"
#include "Crouch.h"
#include "CrouchBlock.h"
#include "Airborne.h"
#include "HitStun.h"
#include "LightAttack.h"
#include "HeavyAttack.h"
#include "LightDash.h"
#include "SlideLight.h"
#include "SlideHeavy.h"
#include "BackDash.h"
#include "ForwardDash.h"